name: Controllo pagina ogni 5 minuti

on:
  schedule:
    - cron: '*/5 * * * *'  # ogni 5 minuti (UTC)
  workflow_dispatch:       # puoi anche avviarlo a mano

jobs:
  run-monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Clona il repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Installa dipendenze
        run: |
          pip install requests

      - name: Esegui lo script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py
